default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_task_development

test:
  <<: *default
  database: your_task_test

production:
  <<: *default
  database: your_task_production
  username: your_task
  password: <%= ENV['your_task_DATABASE_PASSWORD'] %>
