default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manyou_development

test:
  <<: *default
  database: manyou_test

production:
  <<: *default
  database: manyou_production
  username: manyou
  password: <%= ENV['MANYOU_DATABASE_PASSWORD'] %>
